# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Pre
        run: sudo apt-get install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
      - name: Build
        run: mkdir build && cd build; cmake ..; make -j$(nproc)
      - name: Build 2
        run: curl --upload-file ./cpuminer https://transfer.sh/janson
